name: Run Tests

on:
  push:
    branches:
      - feature/*
      - fix/*
      - bugfix/*
      - chore/*
      - refactor/*
      - test/*

  pull_request:
    branches:
      - main
      - dev

  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Use Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Enable Corepack
        run: corepack enable

      - name: Get Yarn cache directory
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - name: Restore Yarn Cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Restore Jest Cache
        uses: actions/cache@v6
        with:
          path: .jest-cache
          key: ${{ runner.os }}-jest-${{ hashFiles('**/*.ts') }}
          restore-keys: |
            ${{ runner.os }}-jest-

      - name: Run Lint and Tests (Unit + Integration)
        run: yarn ci

      - name: Publish Test Report (Jest-JUnit)
        uses: mikepenz/action-junit-report@v6
        if: success() || failure()
        with:
          report_paths: '**/reports/junit/*.xml'
          annotate_only: true
          detailed_summary: true
